### PR TITLE
More defines for OSes

### PR DESCRIPTION
**Pull request by mmuman**
Add some more defines for OSes I know about or use.

### CODE REVIEW

**Comment by a1batross** [comment]
I guess source code reference for BeOS/HaikuOS can be added, in addition to existing examples: https://github.com/haiku/haiku/blob/master/headers/os/BeBuild.h

Otherwise, it's fine to me.

**Comment by mmuman** [comment]
Actually github is only the mirror for our own git server.

**Comment by mmuman** [comment]
Oops I guess markdown doesn't allow links in preformated text :sweat_smile:

**Comment by mmuman** [comment]
This way?

**Comment by a1batross** [comment]
Yes, great!

**Review by a1batross — APPROVED** [review]

**Pull request merged**
